services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    networks:
      - ecommerce-network
    depends_on:
      - db
      - rabbitmq
  
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - ecommerce-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-network

networks:
  ecommerce-network: